spring.application.name=codemate

spring.datasource.url=jdbc:postgresql://localhost:5432/codemate
spring.datasource.username=postgres
spring.datasource.password=postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true